{
 "title": "Mongo connector",
 "description": "Monitor Mongo connector",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_connect_app,env)"
    }
   },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_app,kafka_connect_cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_connect_app{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mongo Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records",
     "type": "stat",
     "description": "\t\nThe total number of records a MongoDB source task passed to the Kafka Connect framework.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Records",
     "type": "timeseries",
     "description": "records\nThe total number of records a MongoDB source task passed to the Kafka Connect framework.\n\nrecords-filtered\nThe number of records a MongoDB source task passed to the Kafka Connect framework that were then filtered by the framework. A filtered record is not written to Kafka.\n\nrecords-acknowledged\nThe total number of records a MongoDB source task passed to the Kafka Connect framework that were then successfully written to Kafka.",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "total - {{connector}}-{{task}}"
      },
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_records_acknowledged{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "acknowledged - {{connector}}-{{task}}"
      },
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_records_filtered{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "filtered - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "stat",
     "description": "\t\nThe total number of bytes a MongoDB source task read from the MongoDB cluster.",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_mongodb_bytes_read{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Average Size of Documents",
     "type": "stat",
     "description": "Perform the following calculation with the mongodb-bytes-read and records metrics",
     "gridPos": { "h": 6, "w": 4, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_mongodb_bytes_read{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"} / kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Latest Mongodb Time Difference",
     "type": "stat",
     "description": "latest-mongodb-time-difference-secs\n\n\t\nThe number of seconds of the most recent time difference recorded between a MongoDB cluster and the post-batch resume token held by a MongoDB source task. This value is calculated by subtracting the timestamp of the task's post-batch resume token from the operationTime value of the most recent successful MongoDB command executed by the task.",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_latest_mongodb_time_difference_secs{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Latest Mongodb Time Difference",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_latest_mongodb_time_difference_secs{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "total - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Task poll duration",
     "type": "timeseries",
     "description": "The total number of milliseconds the Kafka Connect framework spent executing the poll() method of a MongoDB source task.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Task poll duration by range",
     "type": "timeseries",
     "description": "The total number of milliseconds the Kafka Connect framework spent executing the poll() method of a MongoDB source task.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_1_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 1ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_10_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 10ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_100_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 100ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_1000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 1000ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_10000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 10000ms - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Connect Framework poll duration",
     "type": "timeseries",
     "description": "The total number of milliseconds spent executing code in the Kafka Connect framework since the framework first invoked the poll() method of the MongoDB source task. This metric does not count time executing code in the MongoDB sink task towards the total.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Connect Framework poll duration by range",
     "type": "timeseries",
     "description": "The total number of milliseconds spent executing code in the Kafka Connect framework since the framework first invoked the poll() method of the MongoDB source task. This metric does not count time executing code in the MongoDB sink task towards the total.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_1_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 1ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_10_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 10ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_100_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 100ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_1000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 1000ms - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_10000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "> 10000ms - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Initial Commands Successful",
     "type": "stat",
     "description": "The total number of initial commands issued by a MongoDB source task that succeeded. An initial command is a find or aggregate command sent to a MongoDB cluster that retrieves the first set of documents in a cursor. A getMore command is not an initial command.",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_initial_commands_successful{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "GetMore duration",
     "type": "timeseries",
     "description": "\t\nThe total number of milliseconds a MongoDB source task spent executing getMore commands that succeeded.",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_initial_commands_successful_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "GetMore Commands Successful",
     "type": "stat",
     "description": "The total number of getMore commands issued by a MongoDB source task that succeeded.",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_source_task_metrics_getmore_commands_successful{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "GetMore duration",
     "type": "timeseries",
     "description": "\t\nThe total number of milliseconds a MongoDB source task spent executing getMore commands that succeeded.",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_source_task_metrics_getmore_commands_successful_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records",
     "type": "stat",
     "description": "The total number of Kafka records a MongoDB sink task received.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_sink_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Records",
     "type": "timeseries",
     "description": "records-successful\nThe total number of Kafka records a MongoDB sink task successfully wrote to MongoDB.\nrecords-failed\nThe total number of Kafka records a MongoDB sink task failed to write to MongoDB.",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_sink_task_metrics_records_successful{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}",
       "legendFormat": "successful - {{connector}}-{{task}}"
      },
      {
       "expr": "kafka_connect_mongodb_sink_task_metrics_records_failed{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}",
       "legendFormat": "failed - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Latest Kafka Time Difference",
     "type": "stat",
     "description": "The number of milliseconds of the most recent time difference recorded between a MongoDB sink task and Kafka. This value is calculated by subtracting the current time of the connector's clock and the timestamp of the last record the task received.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_sink_task_metrics_latest_kafka_time_difference_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Latest Mongodb Time Difference",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_connect_mongodb_sink_task_metrics_latest_kafka_time_difference_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}",
       "legendFormat": "total - {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Task put duration",
     "type": "timeseries",
     "description": "The total number of milliseconds the Kafka Connect framework spent executing the put() method of a MongoDB sink task.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_sink_task_metrics_in_task_put_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "in Connect framework duration",
     "type": "timeseries",
     "description": "The total number of times code in the Kafka Connect framework executed after the first invocation of the put() method of the MongoDB sink task.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_sink_task_metrics_in_connect_framework_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Processing Phases duration",
     "type": "timeseries",
     "description": "The total number of milliseconds a MongoDB sink task spent processing records before writing them to MongoDB.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_sink_task_metrics_processing_phases_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Batch Writes duration",
     "type": "timeseries",
     "description": "The total number of milliseconds a MongoDB sink task spent successfully writing to the MongoDB cluster.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mongodb_sink_task_metrics_batch_writes_successful_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}[5m])",
       "legendFormat": "successful - {{connector}}-{{task}}"
      },
      {
       "expr": "rate(kafka_connect_mongodb_sink_task_metrics_batch_writes_failed_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"sink-task-[0-9]*\"}[5m])",
       "legendFormat": "failed - {{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_used_bytes{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"})",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      },
      {
       "expr": "jvm_memory_bytes_max{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\",area=\"heap\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM GC time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}