{
 "title": "Gravitino Playground",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Committed Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_total_used / jvm_total_committed) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_heap_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Non-Heap Memory Usage ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_non_heap_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Direct Memory Usage ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_direct_used  / jvm_direct_capacity) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gravitino Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Idle Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gravitino_server_http_server_idle_thread_num",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "gravitino_server_http_request_duration_seconds_count",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Request Statistics",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(gravitino_server_http_request_duration_seconds_count[$__range])) by(operation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(gravitino_server_http_request_duration_seconds_count[$__range])) by(operation) - sum(rate(gravitino_server_5xx_responses_total[$__range])) by(operation))\r\n/\r\nsum(rate(gravitino_server_http_request_duration_seconds_count[$__range])) by(operation) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gravitino_server_http_request_duration_seconds{quantile=\"0.5\"}) by(operation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gravitino_server_http_request_duration_seconds{quantile=\"0.75\"}) by(operation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gravitino_server_http_request_duration_seconds{quantile=\"0.99\"}) by(operation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gravitino_server_1xx_responses_total[$__range])) by(operation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gravitino_server_2xx_responses_total[$__range])) by(operation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gravitino_server_3xx_responses_total[$__range])) by(operation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gravitino_server_4xx_responses_total[$__range])) by(operation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gravitino_server_5xx_responses_total[$__range])) by(operation) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iceberg Rest Server Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle Threads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iceberg_rest_server_http_server_idle_thread_num",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Total Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "iceberg_rest_server_http_request_duration_seconds_count",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Request Statistics",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum(rate(iceberg_rest_server_http_request_duration_seconds_count[$__range])) by(operation) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(iceberg_rest_server_http_request_duration_seconds_count[$__range])) by(operation) - sum(rate(gravitino_server_5xx_responses_total[$__range])) by(operation))\r\n/\r\nsum(rate(iceberg_rest_server_http_request_duration_seconds_count[$__range])) by(operation) * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(iceberg_rest_server_http_request_duration_seconds{quantile=\"0.5\"}) by(operation)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(iceberg_rest_server_http_request_duration_seconds{quantile=\"0.75\"}) by(operation)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(iceberg_rest_server_http_request_duration_seconds{quantile=\"0.99\"}) by(operation)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(iceberg_rest_server_1xx_responses_total[$__range])) by(operation) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(iceberg_rest_server_2xx_responses_total[$__range])) by(operation) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(iceberg_rest_server_3xx_responses_total[$__range])) by(operation) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(iceberg_rest_server_4xx_responses_total[$__range])) by(operation) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(iceberg_rest_server_5xx_responses_total[$__range])) by(operation) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_heap_max", "legendFormat": "Memory Max" },
    { "expr": "jvm_heap_committed", "legendFormat": "Memory Committed" },
    { "expr": "jvm_heap_used", "legendFormat": "Memory Used" }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_non_heap_max", "legendFormat": "Memory Max" },
    { "expr": "jvm_non_heap_committed", "legendFormat": "Memory Committed" },
    { "expr": "jvm_non_heap_used", "legendFormat": "Memory Used" }
   ]
  },
  {
   "title": "Mapped Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_mapped_capacity", "legendFormat": "Memory Capacity" },
    { "expr": "jvm_mapped_used", "legendFormat": "Memory Used" }
   ]
  },
  {
   "title": "JVM CodeHeap Memory Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-NMethods Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1692 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__non_nmethods__usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non-Profiled NMethods Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1692 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__non_profiled_nmethods__usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Profiled NMethods Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1692 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__profiled_nmethods__usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non-NMethods Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1699 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__non_nmethods__max",
       "legendFormat": "Memory Max"
      },
      {
       "expr": "jvm_pools_CodeHeap__non_nmethods__committed",
       "legendFormat": "Memory Committed"
      },
      {
       "expr": "jvm_pools_CodeHeap__non_nmethods__used",
       "legendFormat": " Memory Used"
      }
     ]
    },
    {
     "title": "Non-Profiled NMethods Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1699 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__non_profiled_nmethods__max",
       "legendFormat": "Memory Max"
      },
      {
       "expr": "jvm_pools_CodeHeap__non_profiled_nmethods__committed",
       "legendFormat": "Memory  Committed"
      },
      {
       "expr": "jvm_pools_CodeHeap__non_profiled_nmethods__used",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "Profiled NMethods Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1699 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_CodeHeap__profiled_nmethods__max",
       "legendFormat": "Memory Max"
      },
      {
       "expr": "jvm_pools_CodeHeap__profiled_nmethods__committed",
       "legendFormat": "Memory Committed"
      },
      {
       "expr": "jvm_pools_CodeHeap__profiled_nmethods__used",
       "legendFormat": "Memory Used"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Compressed Class Space Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compressed Class Space Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1939 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_Compressed_Class_Space_usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1939 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_Compressed_Class_Space_max",
       "legendFormat": "Memory Max"
      },
      {
       "expr": "jvm_pools_Compressed_Class_Space_committed",
       "legendFormat": "Memory Committed"
      },
      {
       "expr": "jvm_pools_Compressed_Class_Space_used",
       "legendFormat": "Memory Used"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM G1 Generation Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "G1 Young Generation Count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1950 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_G1_Young_Generation_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "G1 Young Generation Time",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1950 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_G1_Young_Generation_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "G1 Old Generation Count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1950 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_G1_Old_Generation_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "G1 Old Generation Time",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1950 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_G1_Old_Generation_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "G1 Young Generation Average Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1959 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(jvm_G1_Young_Generation_time / jvm_G1_Young_Generation_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "G1 Old Generation Average Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1959 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(jvm_G1_Old_Generation_time / jvm_G1_Old_Generation_count)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM G1 Memory Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "G1 Eden Space Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2056 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_G1_Eden_Space_usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "G1 Old Gen Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2056 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_G1_Old_Gen_usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "G1 Survivor Space Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2056 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_G1_Survivor_Space_usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "G1 Eden Space Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2063 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_G1_Eden_Space_committed",
       "legendFormat": "Memory Committed"
      },
      { "expr": "jvm_pools_G1_Eden_Space_used", "legendFormat": " Memory Used" },
      {
       "expr": "jvm_pools_G1_Eden_Space_used_after_gc",
       "legendFormat": "Used After GC"
      }
     ]
    },
    {
     "title": "G1 Old Gen Space Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2063 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_pools_G1_Old_Gen_committed", "legendFormat": "Memory Committed" },
      { "expr": "jvm_pools_G1_Old_Gen_used", "legendFormat": " Memory Used" },
      {
       "expr": "jvm_pools_G1_Old_Gen_used_after_gc",
       "legendFormat": "Used After GC"
      }
     ]
    },
    {
     "title": "G1 Survivor Space Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2063 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_pools_G1_Survivor_Space_committed",
       "legendFormat": "Memory Committed"
      },
      {
       "expr": "jvm_pools_G1_Survivor_Space_used",
       "legendFormat": " Memory Used"
      },
      {
       "expr": "jvm_pools_G1_Survivor_Space_used_after_gc",
       "legendFormat": "Used After GC"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metaspace Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metaspace Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2083 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_pools_Metaspace_usage * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2083 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_pools_Metaspace_max", "legendFormat": "Memory Max" },
      { "expr": "jvm_pools_Metaspace_committed", "legendFormat": "Memory Committed" },
      { "expr": "jvm_pools_Metaspace_used", "legendFormat": "Memory Used" }
     ]
    }
   ]
  }
 ]
}