global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 15s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus-1:9090']

  - job_name: etcd
    static_configs:
      - targets: ["etcd-1:2381"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['prometheus-pushgateway:9091']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-nodeexporter:9100']

  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka-1:1234"
          - "kafka-2:1234"
          - "kafka-3:1234"
        labels:
          env: "dev"

  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper-1:1234"
          - "zookeeper-2:1234"
          - "zookeeper-3:1234"
        labels:
          env: "dev"

  - job_name: "connect"
    static_configs:
      - targets:
          - "connect-1:1234"
          - "connect-2:1234"
        labels:
          env: "dev"
          cluster: "cluster1"

  - job_name: "streams-demo"
    static_configs:
      - targets:
          - "streams-demo:1234"
        labels:
          env: "dev"

  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schema-registry-1:1234"
        labels:
          env: "dev"

  - job_name: "ksqldb"
    static_configs:
      - targets:
          - "ksqldb-server-1:1234"
          - "ksqldb-server-2:1234"
        labels:
          env: "dev"

  - job_name: "restproxy"
    static_configs:
      - targets:
          - "kafka-rest-1:1234"
        labels:
          env: "dev"

  # No producer for the moment in cp-demo
  #  - job_name: 'producer'
  #    static_configs:
  #      - targets:
  #          - 'producer:1234'
  #        labels:
  #          env: 'dev'

  # No consumer for the moment in cp-demo
  #  - job_name: 'consumer'
  #    static_configs:
  #      - targets:
  #          - "consumer:1234"
  #        labels:
  #          env: 'dev'

  - job_name: "kafka-lag-exporter"
    static_configs:
      - targets:
          - "kafka-lag-exporter:9999"
        labels:
          env: "dev"

  - job_name: risingwave-compute-1
    static_configs:
      - targets: ["risingwave-compute-1:1222"]

  - job_name: risingwave-meta-1
    static_configs:
      - targets: ["risingwave-meta-1:1250"]

  - job_name: risingwave-compactor-1
    static_configs:
      - targets: ["risingwave-compactor-1:1260"]

  - job_name: risingwave-frontend-1
    static_configs:
      - targets: ["risingwave-frontend-1:2222"]

  - job_name: risingwave-connector
    static_configs:
      - targets: ["risingwave-connector-1:50052"]

  - job_name: minio-1
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio-1:9000"]
      
  - job_name: redis_exporter
    static_configs:
    - targets: ['redis-exporter:9121']      

  - job_name: zipkin
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']