organization:
  name: "${ORGANISATION_NAME}"
  
clusters:
  - id: default
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}"
    properties: |
      client.id=conduktor
      default.api.timeout.ms=5000
      request.timeout.ms=5000
    schemaRegistry:
      url: "${SCHEMA_REGISTRY_URL:-http://localhost:8081}"
      ignoreUntrustedCertificate: false
      properties:
    kafkaConnects:
      - url: "${KAFKA_CONNECT_URL:-http://localhost:8083}"
        id: kafka-connect
        name: kafkaConnect      

    labels:
      env: default


auth:
  local-users:
    - email: "${ADMIN_EMAIL}"
      password: "${ADMIN_PSW}"

license: ${LICENSE_KEY:-~} # Fallback to null (~)
