{
 "title": "XTDB: Monitoring Dashboard 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "How many current active XTDB nodes are there?",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jvm_threads_live_threads{node_id=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Lag",
   "type": "timeseries",
   "description": "How far behind is each node on it's indexing? Ie - id of last-submitted transaction - id of last-completed-transaction?",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "targets": [
    { "expr": "node_tx_lag_MsgId", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "Max Transaction Latency (Over Time)",
   "type": "stat",
   "description": "What's the highest transaction latency over the time period?",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(tx_op_timer_seconds_max[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Query Latency (Over Time)",
   "type": "stat",
   "description": "What's the Max Query latency over the current time period?",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(query_timer_seconds_max[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Transactions",
   "type": "timeseries",
   "description": "How many transactions are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(tx_op_timer_seconds_count[30s]))",
     "legendFormat": "Cluster Rate"
    }
   ]
  },
  {
   "title": "Cluster Transactions Latencies",
   "type": "timeseries",
   "description": "How long are transactions taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, tx_op_timer_seconds)",
     "legendFormat": "Cluster Average"
    },
    {
     "expr": "quantile(0.99, tx_op_timer_seconds)",
     "legendFormat": "Cluster 99%"
    }
   ]
  },
  {
   "title": "Cluster Transaction Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(tx_error_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster Queries",
   "type": "timeseries",
   "description": "How many Queries are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(query_timer_seconds_count[30s]))",
     "legendFormat": "Cluster Rate"
    }
   ]
  },
  {
   "title": "Cluster Query Latencies",
   "type": "timeseries",
   "description": "How long are queries taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, query_timer_seconds)",
     "legendFormat": "Cluster Average"
    },
    {
     "expr": "quantile(0.99, query_timer_seconds)",
     "legendFormat": "Cluster 99%"
    }
   ]
  },
  {
   "title": "Cluster Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(query_error_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster PGWire Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pgwire_active_connections)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster PGWire Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pgwire_connections_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster Buffer Pool Network Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(buffer_pool_network_write_total)",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Cluster Buffer Pool Network Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(buffer_pool_network_read_total)",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  { "title": "$xtdbnode - Node Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "xtdbnode" },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "How many transactions are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}[30s]))",
     "legendFormat": "$xtdbnode - rate"
    }
   ]
  },
  {
   "title": "Transactions Latencies",
   "type": "timeseries",
   "description": "How long are transactions taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, tx_op_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - Average"
    },
    {
     "expr": "quantile(0.99, tx_op_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - 99%"
    }
   ]
  },
  {
   "title": "Transaction Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tx_error_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "How many Queries are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(query_timer_seconds_count{node_id=\"$xtdbnode\"}[30s]))",
     "legendFormat": "$xtdbnode - Rate"
    }
   ]
  },
  {
   "title": "Query Latencies",
   "type": "timeseries",
   "description": "How long are queries taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, query_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - Average"
    },
    {
     "expr": "quantile(0.99, query_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - 99%"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "query_error_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "PGWire Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgwire_active_connections{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "PGWire Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgwire_connections_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Buffer Pool Network Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "buffer_pool_network_write_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Buffer Pool Network Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "buffer_pool_network_read_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "description": "Current Percentage of CPU used by JVM process of the XTDB nodes. \n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage over Time",
   "type": "timeseries",
   "description": "Percentage of CPU used by JVM process of the XTDB node over time.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "description": "Heap memory used by the JVM process of each node over time.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(node_id) (jvm_memory_used_bytes{node_id=\"$xtdbnode\", area=\"heap\"})",
     "legendFormat": "{{node_id}} - used memory"
    },
    {
     "expr": "sum by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\", area=\"heap\"})",
     "legendFormat": "{{node_id}}  - committed memory"
    },
    {
     "expr": "max(sum by(node_id) (jvm_memory_max_bytes{node_id=\"$xtdbnode\", area=\"heap\"}))",
     "legendFormat": "Max Heap Size"
    }
   ]
  }
 ]
}