{
 "title": "XTDB: Node Debugging Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Max"
    }
   ]
  },
  { "title": "XTDB - Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Transactions - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Quantiles)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Query - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "query_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "query_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "query_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "JVM - Heap Usage (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Heap Usage (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Buffer Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node_id) (jvm_buffer_memory_used_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{state}}"
    }
   ]
  },
  { "title": "XTDB - Direct Allocated Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "XTDB - Buffer Pool Allocated Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memory_cache_evictableBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} evictable bytes"
    },
    {
     "expr": "memory_cache_freeBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} free bytes"
    },
    {
     "expr": "memory_cache_pinnedBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} pinned bytes"
    }
   ]
  },
  {
   "title": "XTDB - Compactor Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "compactor_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Indexer Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "indexer_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Live Index Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "live_index_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Log Watcher Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "watcher_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Netty Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_netty_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - netty used memory"
    }
   ]
  },
  {
   "title": "Direct Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - direct used memory"
    }
   ]
  },
  { "title": "XTDB - Memory Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Memory Cache - Record Batch count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_sliceCount{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} Meta Record Batches"
    },
    {
     "expr": "memory_cache_dataFiles_sliceCount{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data Record Batches"
    }
   ]
  },
  {
   "title": "Memory Cache - Weights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_weightBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta Record Batches weight"
    },
    {
     "expr": "memory_cache_dataFiles_weightBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data Record Batches weight"
    }
   ]
  },
  {
   "title": "Memory Cache - Pinned vs Unpinned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_pinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta pinned"
    },
    {
     "expr": "memory_cache_metaFiles_unpinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta unpinned"
    },
    {
     "expr": "memory_cache_dataFiles_pinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data pinned"
    },
    {
     "expr": "memory_cache_dataFiles_unpinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data unpinned"
    }
   ]
  },
  {
   "title": "Memory Cache - Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "rate(memory_cache_misses_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} Memory Cache Misses 1min"
    },
    {
     "expr": "rate(disk_cache_misses_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Disk Cash Misses 1min"
    },
    {
     "expr": "rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Record Batch Requests 1min"
    },
    {
     "expr": "avg_over_time(rate(memory_cache_misses_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} Memory Cache Misses 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    }
   ]
  },
  {
   "title": "Buffer Pool - Record Batch requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Record Batch requests 1min"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch requests 5min avg"
    }
   ]
  },
  { "title": "XTDB - Compactor Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Available Compaction Jobs",
   "type": "timeseries",
   "description": "Number of currently available compactor jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "compactor_jobs_available{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Available Compactor Jobs"
    }
   ]
  },
  {
   "title": "Compaction Job Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(node_id) (compactor_job_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}} - Average"
    },
    {
     "expr": "compactor_job_timer_seconds{quantile=\"0.99\", node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - 99%"
    },
    {
     "expr": "compactor_job_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Max"
    }
   ]
  }
 ]
}