{
 "title": "NiFi PrometheusReportingTask Dashboard With Job And Instance",
 "description": "A complete dashboard for all metrics exposed using PrometheusReportingTask",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(nifi_amount_bytes_read,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nifi_amount_bytes_read{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_jvm_uptime{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_heap_usage{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_heap_used{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Deamon Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_daemon_thread_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Heap Non Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_heap_non_usage{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_gc_time{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{gc_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_gc_runs{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " {{gc_name}}"
    }
   ]
  },
  {
   "title": "JVM File Descriptor Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_file_descriptor_usage{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_jvm_thread_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Lineage Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_average_lineage_duration{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Terminated Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_terminated{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_active{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlowFiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Received FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_received{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Transferred FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_transferred{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_sent{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Removed FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_removed{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Input Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_input{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Output Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_output{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Queued Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_queued{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Contents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Input Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_input_total{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Output Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_output_total{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Queued Content",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_queued_total{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backpressure Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_bytes_threshold{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_object_threshold{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Enabled",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_enabled{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transferred Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_transferred{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_received{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Written Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_written{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_sent{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_read{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  }
 ]
}