{
 "title": "NiFi Monitor",
 "tags": [ "nifi" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Nodes Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "flow/cluster/summary",
     "select": [
      [
       {
        "params": [
         "clusterSummary.connectedNodeCount"
        ],
        "type": "field"
       }
      ],
      [
       { "params": [ "clusterSummary.totalNodeCount" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Status - Processors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"flow/status\" and\n    r._field == \"controllerStatus.runningCount\" or r._field == \"controllerStatus.disabledCount\" or r._field == \"controllerStatus.stoppedCount\" or r._field == \"controllerStatus.syncFailureCount\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Files in Queue Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"flow/status\" and (r._field == \"controllerStatus.flowFilesQueued\"))\n  |> window(every: 5m)\n  |> toFloat()\n  |> median()\n  |> group(columns: [\"_time\", \"_start\", \"_stop\", \"_value\"], mode: \"except\")\n  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall FlowFiles Queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Flow Files Queued",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/status",
     "query": "SELECT sum(\"controllerStatus.flowFilesQueued\") FROM \"flow/status\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "controllerStatus.flowFilesQueued"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Files Queued - Per Connection",
   "type": "stat",
   "description": "Per connection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"flow/process-groups/root\" and \n  r._field == \"processGroupFlow.flow.connections.0.status.aggregateSnapshot.flowFilesQueued\" or \n  r._field == \"processGroupFlow.flow.connections.1.status.aggregateSnapshot.flowFilesQueued\" or \n  r._field == \"processGroupFlow.flow.connections.2.status.aggregateSnapshot.flowFilesQueued\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Files Processed",
   "type": "stat",
   "description": "Per Connection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Connection 1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "query": "SELECT sum(\"processGroupFlow.flow.connections.0.status.aggregateSnapshot.flowFilesOut\") FROM \"flow/process-groups/root\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.0.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Connection 2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "query": "SELECT sum(\"processGroupFlow.flow.connections.1.status.aggregateSnapshot.flowFilesOut\") FROM \"flow/process-groups/root\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.1.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Connection 3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "query": "SELECT sum(\"processGroupFlow.flow.connections.2.status.aggregateSnapshot.flowFilesOut\") FROM \"flow/process-groups/root\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.2.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Utilisation %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Heap Utilization %",
     "measurement": "system-diagnostics?nodewise=true",
     "query": "import \"strings\"\nfrom(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"system-diagnostics\" )\n  |> filter(fn: (r) => r._field == \"systemDiagnostics.aggregateSnapshot.heapUtilization\")\n  |> map(fn: (r) => ({\n      r with\n      _value: strings.substring(v: r._value, start: 0, end: 4)\n    })\n  )\n  |> toFloat()\n  |> aggregateWindow(every: 5m, fn: mean)",
     "select": [
      [
       {
        "params": [
         "systemDiagnostics.aggregateSnapshot.heapUtilization"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total KBs Queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total KBs Queued",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/status",
     "select": [
      [
       { "params": [ "controllerStatus.bytesQueued" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Files In",
   "type": "stat",
   "description": "Per Connection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Connection 1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.0.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Coonection 2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.1.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Connection 3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/process-groups/root",
     "select": [
      [
       {
        "params": [
         "processGroupFlow.flow.connections.2.status.aggregateSnapshot.flowFilesIn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow FileRepository Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system-diagnostics\" and \n  r._field == \"systemDiagnostics.aggregateSnapshot.flowFileRepositoryStorageUsage.usedSpaceBytes\" or r._field == \"systemDiagnostics.aggregateSnapshot.flowFileRepositoryStorageUsage.totalSpaceBytes\"\n  or r._field == \"systemDiagnostics.aggregateSnapshot.flowFileRepositoryStorageUsage.freeSpaceBytes\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running,Stopped,Disabled Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running Count",
     "measurement": "flow/status",
     "select": [
      [
       { "params": [ "controllerStatus.runningCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Disabled Count",
     "measurement": "flow/status",
     "select": [
      [
       { "params": [ "controllerStatus.disabledCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Stopped Count",
     "measurement": "flow/status",
     "select": [
      [
       { "params": [ "controllerStatus.stoppedCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SyncFailure Count",
     "measurement": "flow/status",
     "select": [
      [
       {
        "params": [
         "controllerStatus.syncFailureCount"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total FlowFiles in Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"nifi/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"flow/status\" and (r._field == \"controllerStatus.flowFilesQueued\"))\n  |> window(every: 5m)\n  |> toFloat()\n  |> median()\n  |> group(columns: [\"_time\", \"_start\", \"_stop\", \"_value\"], mode: \"except\")\n  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WIP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "controller/cluster",
     "select": [
      [
       { "params": [ "cluster.nodes.0.queued" ], "type": "field" }
      ],
      [
       { "params": [ "cluster.nodes.1.queued" ], "type": "field" }
      ],
      [
       { "params": [ "cluster.nodes.2.queued" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "flow/status",
     "select": [
      [
       { "params": [ "controllerStatus.queued" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Thread Count",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow/status",
     "select": [
      [
       {
        "params": [
         "controllerStatus.activeThreadCount"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}