{
 "title": "Metabase",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "title": "Web Server ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Web Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(code) (rate(jetty_responses_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jetty_requests_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap / Nonheap size",
   "type": "timeseries",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{area}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap / Nonheap size",
   "type": "timeseries",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Database Connection Pool (C3P0) ($database)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "c3p0_num_connections{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "database=\"{{database}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Number of threads awaiting checkout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "c3p0_num_threads_awaiting_checkout_default_user{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "database=\"{{database}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Number of busy connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "c3p0_num_busy_connections{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "database=\"{{database}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Number of idle connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "c3p0_num_idle_connections{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "database=\"{{database}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Minimum Pool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "c3p0_min_pool_size{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "database=\"{{database}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Maximum Pool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "c3p0_max_pool_size{job=~\"$job\", instance=~\"$instance\", database=~\"$database\"}",
     "legendFormat": "Maximum pool size (database=\"{{database}}\", instance=\"{{instance}}\")"
    }
   ]
  },
  { "title": "Search ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Number of respond errors",
   "type": "timeseries",
   "description": "Number of errors when responding to search requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(metabase_search_response_error_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time of filtering search results",
   "type": "timeseries",
   "description": "Total number of ms spent filtering search results by collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(metabase_search_semantic_collection_filter_ms_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time of looking up candidate document details",
   "type": "timeseries",
   "description": "Total number of ms the semantic search indexer spent looking up candidate document details",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(metabase_search_semantic_collection_filter_ms_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rows in the active semantic index DLQ table",
   "type": "timeseries",
   "description": "Number of rows in the active semantic index dead-letter-queue table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "metabase_search_semantic_dlq_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful semantic search DLQ retries",
   "type": "timeseries",
   "description": "Number of successful semantic search DLQ retries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "metabase_search_semantic_indexer_dlq_successes_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Semantic Indexer Poll Timing Distribution",
   "type": "bargauge",
   "description": "Distribution of time elapsed between semantic search indexer polls (pg clock)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (metabase_search_semantic_indexer_poll_to_poll_interval_ms_bucket{instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time of filtering readable docs",
   "type": "timeseries",
   "description": "Total number of ms spent filtering readable docs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(metabase_search_semantic_permission_filter_ms_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Notification ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Notification Error",
   "type": "gauge",
   "description": "Number of errors when sending notifications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metabase_notification_send_error_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent notification sends",
   "type": "timeseries",
   "description": "Number of concurrent notification sends.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "metabase_notification_concurrent_tasks{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Card Notification Waiting Duration",
   "type": "gauge",
   "description": "Duration in milliseconds that notifications wait in the processing queue before being picked up for delivery (card).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (metabase_notification_wait_duration_ms_bucket{instance=~\"$instance\", payload_type=\"notification/card\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Dashboard Notification Waiting Duration",
   "type": "gauge",
   "description": "Duration in milliseconds that notifications wait in the processing queue before being picked up for delivery (dashboard).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (metabase_notification_wait_duration_ms_bucket{instance=~\"$instance\", payload_type=\"notification/dashboard\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}