{
 "title": "Trino loadbalancer",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(queued_queries,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running queries per clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(cluster) (cluster_queries{state=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued queries per cluster group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max by(cluster_group) (queued_queries)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(query_queued_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(query_queued_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(query_queued_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(query_queued_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cluster" } },
   "targets": [
    {
     "expr": "max by(cluster_group) (cluster_counts_per_state{state=~\"Ready|Draining\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(resource) (rate(http_requests_total_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}