{
 "title": "Debezium Connectors",
 "description": "Monitoring Dashboard for Debezium connector",
 "tags": [
  "mysql",
  "debezium",
  "postgres",
  "mongodb",
  "sqlserver"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Server",
    "query": {
     "query": "debezium_metrics_MilliSecondsSinceLastEvent"
    }
   },
   {
    "name": "instance",
    "label": "Connector Node",
    "query": {
     "query": "debezium_metrics_MilliSecondsSinceLastEvent"
    }
   }
  ]
 },
 "panels": [
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "\n# Debezium Connector Metrics\n\nThe Debezium connectors has three metric types:\n\n* snapshot metrics\n\n* binlog metrics (MySql)\n\n* schema history metrics (MySql and SQLServer)\n\nFor more detailed informarion about the metrics please visit the Debezium documentation page\n\n[Click here to visit](https://debezium.io/documentation/reference/stable/operations/monitoring.html)\n\n\n\n"
   }
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Binlog Position (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_BinlogPosition{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "GTID Enabled (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_IsGtidModeEnabled{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "RolledBack Transactions (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfRolledBackTransactions{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Not WellFormed Transactions (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfNotWellFormedTransactions{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\r\n"
    }
   ]
  },
  {
   "title": "Total Number Of Events Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfSkippedEvents{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Events Filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Since Last Event",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Behind Master (MySql only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_SecondsBehindMaster{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Disconnects (MySql and Mongo only)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfDisconnects{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Large Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfLargeTransactions{context=\"streaming\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Holding GlobalLock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_HoldingGlobalLock{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Events Filtered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Time Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Erroneous Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Events Seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Schema Changes info",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "options": {
    "content": "\n# Schema Changes Metrics\n\nFor detailed explanation for all the schema changes metrics: [Visit Debezium documentation](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-schema-history-metrics)\n\n\n\n\n"
   }
  },
  {
   "title": "Recovery StartTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RecoveryStartTime{context=\"schema-history\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastAppliedChange{context=\"schema-history\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastRecoveredChange{context=\"schema-history\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesRecovered{context=\"schema-history\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",instance=\"$instance\",job=\"kafka-connect\",name=\"$name\"}\t\r",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  }
 ]
}