{
 "title": "OTel - kafkametrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(kafka_consumer_group_lag_ratio,group)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_partition_replicas,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Brokers",
   "type": "stat",
   "description": "Number of brokers in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Replicas for topic",
   "type": "table",
   "description": "Number of replicas for partition of topic",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(topic) (kafka_partition_replicas{topic=~\"$topic\"})",
     "legendFormat": "Topic: {{topic}} -  Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "table",
   "description": "Number of partitions in topic",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=~\"$topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "description": "Current approximate sum of consumer group lag across all partitions of topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kafka_consumer_group_lag_sum_ratio{group=~\"$group\", topic=~\"$topic\"}",
     "legendFormat": "Group: {{group}} Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Partition)",
   "type": "timeseries",
   "description": "Current approximate lag of consumer group at partition of topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "kafka_consumer_group_lag_ratio{group=~\"$group\", topic=~\"$topic\"}",
     "legendFormat": "Group: {{group}} Topic: {{topic}} Partition: {{partition}}"
    }
   ]
  }
 ]
}