name: Prometheus Node Exporter
id: prometheus-nodeexporter
category:
  id: 09_storage
  name: storage
  color: purple
arch: [x86-64, arm]

links:
  website: https://prometheus.io/
  documentation: https://prometheus.io/docs/guides/node-exporter/#monitoring-linux-host-metrics-with-the-node-exporter
  github: https://github.com/prometheus/node_exporter

description: >
  The Prometheus Node Exporter exposes a wide variety of hardware- and
  kernel-related metrics.

enable:
  platys_init: PROMETHEUS,PROMETHEUS_NODEEXPORTER
  example: |
    platys init --enable-services PROMETHEUS,PROMETHEUS_NODEEXPORTER
    platys gen

parameters:
  - name: PROMETHEUS_NODEEXPORTER_enable
    default: "false"
    since: "1.17.0"
    description: >
      Generate Prometheus Node Exporter service
