name: Prometheus Alertmanager
id: prometheus-alertmanager
category:
  id: 09_storage
  name: storage
  color: purple
arch: [x86-64, arm]

links:
  website: https://prometheus.io/
  documentation: https://prometheus.io/docs/alerting/latest/alertmanager/
  github: https://github.com/prometheus/alertmanager

description: >
  Handles alerts sent by client applications such as the Prometheus server. It
  takes care of deduplicating, grouping, and routing them to the correct
  receiver integration such as email, PagerDuty, or OpsGenie. It also takes
  care of silencing and inhibition of alerts.

enable:
  platys_init: PROMETHEUS,PROMETHEUS_ALERTMANAGER
  example: |
    platys init --enable-services PROMETHEUS,PROMETHEUS_ALERTMANAGER
    platys gen

usage:
  - title: Usage
    content: |
      Navigate to <http://dataplatform:28328>

parameters:
  - name: PROMETHEUS_ALERTMANAGER_enable
    default: "false"
    since: "1.17.0"
    description: >
      Generate Prometheus Alertmanager service
