name: Prometheus
id: prometheus
category:
  id: 09_storage
  name: storage
  color: purple
arch: [x86-64, arm]

links:
  website: https://prometheus.io/
  documentation: https://prometheus.io/docs/introduction/overview/
  github: https://github.com/prometheus/prometheus

description: >
  The Prometheus monitoring system and time series database.

enable:
  platys_init: PROMETHEUS
  example: |
    platys init --enable-services PROMETHEUS
    platys gen

usage:
  - title: Usage
    content: |
      Navigate to <http://dataplatform:9090/graph>

parameters:
  - name: PROMETHEUS_enable
    default: "false"
    since: "1.1.0"
    description: >
      Generate Prometheus service

  - name: PROMETHEUS_volume_map_data
    default: "false"
    since: "1.1.0"
    description: >
      Volume map data folder into the Prometheus service

  - name: PROMETHEUS_volume_map_custom_config
    default: "false"
    since: "1.17.0"
    description: >
      Volume map custom config
      (`./custom-conf/prometheus/prometheus-config/prometheus.yml`) into the
      Prometheus service.
