#!/bin/sh

while getopts u:a:f: flag
do
    case "${flag}" in
        i) cluster_id=${OPTARG};;
        u) users=${OPTARG};;
    esac
done


kafka-storage format --ignore-formatted -c /etc/kafka/kafka.properties" --cluster_id $cluster_id --add-scram 'SCRAM-SHA-256=[name=broker,password=broker-secret]'
