apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: grafana
    url: http://influxdb:8086
    basicAuth: false
    jsonData:
      dbName: nifi
      httpMode: POST
    secureJsonData:
      password: root
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: false
    jsonData:
      version: Flux
      organization: nifi
      defaultBucket: "nifi/autogen"
      tlsSkipVerify: true
    secureJsonData:
      token: "root:root"
