apiVersion: 1

datasources:

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Mimir