apiVersion: 1

datasources:
  - name: risingwave
    type: postgres
    access: proxy
    orgId: 1
    url: "risingwave:4566"
    editable: true
    isDefault: false
    user: ${RISINGWAVE_USER}
    database: ${RISINGWAVE_DB}
    secureJsonData:
      password: ${RISINGWAVE_PASSWORD}
    jsonData:
      database: ${RISINGWAVE_DB}
      sslmode: 'disable'
      postgresVersion: 1200