apiVersion: 1

datasources:
  - name: timescaledb
    type: postgres
    orgId: 1
    url: "timescaledb:5432"
    editable: true
    isDefault: true
    user: ${TIMESCALEDB_USER}
    database: ${TIMESCALEDB_DB}
    secureJsonData:
      password: ${TIMESCALEDB_PASSWORD}
    jsonData:
      database: ${TIMESCALEDB_DB}
      sslmode: 'disable'
      timescaledb: true
      postgresVersion: 1200