apiVersion: 1

datasources:
  - name: ES - Tickets by created_at
    type: elasticsearch
    uid: DS_ES_TICKETS_BY_CREATED_AT
    access: proxy
    url: http://zammad-elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_ticket"
      timeField: "created_at"
      maxConcurrentShardRequests: 5
      includeFrozen: false

  - name: ES - Tickets by closed_at
    type: elasticsearch
    uid: DS_ES_TICKETS_BY_CLOSED_AT
    access: proxy
    url: http://zammad-elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_ticket"
      timeField: "close_at"
      maxConcurrentShardRequests: 5
      includeFrozen: false

  - name: ES - Ticket Articles
    type: elasticsearch
    uid: DS_ES_TICKET_ARTICLES
    access: proxy
    url: http://zammad-elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_ticket_article"
      timeField: "created_at"
      maxConcurrentShardRequests: 5
      includeFrozen: false

  - name: ES - CTI Log
    type: elasticsearch
    uid: DS_ES_CTI_LOG
    access: proxy
    url: http://zammad-elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_cti_log"
      timeField: "start_at"
      maxConcurrentShardRequests: 5
      includeFrozen: false

  - name: ES - Chat Sessions
    type: elasticsearch
    uid: DS_ES_CHAT_SESSIONS
    access: proxy
    url: http://zammad-elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_chat_session"
      timeField: "created_at"
      maxConcurrentShardRequests: 5
      includeFrozen: false
