# /etc/grafana/provisioning/datasources/cti-log.yaml
apiVersion: 1

datasources:
  - name: ES - CTI Log
    type: elasticsearch
    uid: DS_ES_-_CTI_LOG        # must match the ${...} placeholder in the dashboard JSON
    access: proxy
    url: http://zammad-elasticsearch:9200  # replace with your ES host
    isDefault: false
    editable: true
    jsonData:
      esVersion: "9.0.0"
      index: "zammad_production_cti_log"       # replace with your actual index pattern
      timeField: "@start_at"   # replace with your actual time field
      logMessageField: "message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
      includeFrozen: false