name: build-platys-modern-dataplatform

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      run: |
        docker buildx build \
          --tag trivadis/platys-modern-data-platform:1.17.0-preview \
          --platform linux/amd64,linux/arm/v7,linux/arm64 . 
