{
 "title": "Trino Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(trino_execution_QueryManager_RunningQueries, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(java_lang_Memory_HeapMemoryUsage_used{namespace=\"$namespace\"}) by (pod, job)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(java_lang_Threading_ThreadCount{namespace=\"$namespace\"}) by (pod, job)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(java_lang_OperatingSystem_CpuLoad{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Size (OS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(java_lang_OperatingSystem_TotalMemorySize{namespace=\"$namespace\"}) by (pod) / (1024^3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heartbeat Worker Node Failure Detector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trino_failuredetector_HeartbeatFailureDetector_ActiveCount{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Active Nodes"
    },
    {
     "expr": "sum(trino_failuredetector_HeartbeatFailureDetector_FailedCount{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Failed Nodes"
    }
   ]
  },
  {
   "title": "Cluster Memory Pool Free Distributed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(trino_memory_ClusterMemoryPool_FreeDistributedBytes{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Free Distributed Bytes"
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Running Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_RunningQueries{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_QueuedQueries{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Fully Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_FullyBlockedQueries{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Fully Blocked"
    }
   ]
  },
  {
   "title": "Queries Killed Due To Out Of Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Queries Killed (Out of Memory)"
    }
   ]
  },
  {
   "title": "Failed Queries (5m Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(trino_execution_QueryManager_FailedQueries_FiveMinute_Count{namespace=\"$namespace\"}[5m])) by (job)",
     "legendFormat": "Failed Queries (5m Rate)"
    }
   ]
  },
  {
   "title": "Completed Queries (Since Last Cluster Start))",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_CompletedQueries_TotalCount{namespace=\"$namespace\"})",
     "legendFormat": "Completed Queries "
    }
   ]
  },
  {
   "title": "Query Execution Time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_ExecutionTime_AllTime_P95{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Wall Input Bytes Rate (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(trino_execution_QueryManager_WallInputBytesRate_AllTime_Avg{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "Wall Input Bytes Rate"
    }
   ]
  },
  {
   "title": "Trino SQL Tasks -  Input Data Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(trino_execution_SqlTaskManager_InputDataSize_FiveMinute_Count{namespace=\"$namespace\"}) by (pod) / (1024^3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trino SQL Tasks -  Input Data Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(trino_execution_SqlTaskManager_InputPositions_FiveMinute_Count{namespace=\"$namespace\"}) by (job) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}